BOARD_SIZE = 15

WORDS = [
    "TRADUCTOR", "CAMARERA", "EMPLEADO",
    "RELOJERO", "APICULTOR", "ATLETA",
    "ASTRONAUTA", "CONDUCTOR", "JOYERO",
    "CIRUJANO", "FOTOGRAFO", "MODISTA",
    "GEOLOGO", "JUEZ", "MODELO"
]
